apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  namespace: infra-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
        - name: mailpit
          image: axllent/mailpit:latest
          ports:
            - containerPort: 1025 # Mailing Port (SMTP)
            - containerPort: 8025 # Web UI Port
          env:
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mailer-smtp-secret
                  key: smtp-username
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailer-smtp-secret
                  key: smtp-password
