apiVersion: batch/v1
kind: Job
metadata:
  name: redis-bulk-seeder
  namespace: infra-system
spec:
  template:
    metadata:
      labels:
        app: redis-bulk-seeder
    spec:
      containers:
        - name: redis-bulk-seeder
          image: rmat98/redis-seeder:v1.0.1
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: port
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: password
      restartPolicy: Never
  backoffLimit: 4
