apiVersion: v1
kind: Service
metadata:
  name: go-backend-service
  namespace: banking-apps
  labels:
    app: mailer-service
spec:
  selector:
    app: mailer-service
  ports:
    - name: go-http-metrics
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
