server:
  port: 8080

camel:
  component:
    kafka:
      # Using internal Kafka bootstrap address for in-cluster communication
      brokers: ${KAFKA_BROKERS:main-cluster-kafka-bootstrap.infra-system.svc:9093}
      security-protocol: SSL
      # ssl-endpoint-algorithm: ""

      ssl-truststore-location: /app/certs/ca.p12
      ssl-truststore-type: PKCS12
      ssl-truststore-password: ${KAFKA_TRUSTSTORE_PASSWORD}

      ssl-keystore-location: /app/certs/user.p12
      ssl-keystore-type: PKCS12
      ssl-keystore-password: ${KAFKA_KEYSTORE_PASSWORD}

# --- ΕΔΩ ΜΠΑΙΝΕΙ ΤΟ ACTUATOR, ΚΑΘΑΡΟ ΚΑΙ ΑΝΕΞΑΡΤΗΤΟ ---
management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health"
  endpoint:
    prometheus:
      enabled: true
