apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: infra-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.4-alpine
          ports:
            - containerPort: 6379
---
# --- REDIS INSIGHT (Το UI) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-insight
  namespace: infra-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-insight
  template:
    metadata:
      labels:
        app: redis-insight
    spec:
      containers:
        - name: redis-insight
          image: redis/redisinsight:latest
          ports:
            - containerPort: 5540
          resources:
            limits:
              memory: "256Mi"
              cpu: "300m"
            requests:
              memory: "128Mi"
              cpu: "150m"
