apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: cobol-backend-user
  namespace: infra-system
  labels:
    strimzi.io/cluster: main-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "balance-requests"
          patternType: literal
        operations:
          - Read
          - Describe
      - resource:
          type: topic
          name: "balance-responses"
          patternType: literal
        operations:
          - Write
          - Describe
      - resource:
          type: group
          name: "cobol-backend-group"
          patternType: literal
        operations:
          - Read
          - Write
          - Describe
  template:
    secret:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "banking-apps"
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: java-microservice-user
  namespace: infra-system
  labels:
    strimzi.io/cluster: main-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "balance-requests"
          patternType: literal
        operations:
          - Write
          - Describe
      - resource:
          type: group
          name: "java-microservice-group"
          patternType: literal
        operations:
          - Read
          - Write
          - Describe
  template:
    secret:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "banking-apps"
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: go-microservice-user
  namespace: infra-system
  labels:
    strimzi.io/cluster: main-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "balance-responses"
          patternType: literal
        operations:
          - Read
          - Describe
      - resource:
          type: topic
          name: "profile-updates"
          patternType: literal
        operations:
          - Read # For testing, the Go microservice will also consume profile updates to enrich responses
          - Write
          - Describe
      - resource:
          type: group
          name: "go-microservice-group"
          patternType: literal
        operations:
          - Read
          - Write
          - Describe
      - resource:
          type: group
          name: "test-go-microservice-group"
          patternType: literal
        operations:
          - Read
          - Write
          - Describe
  template:
    secret:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "banking-apps"
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: go-mailer-user
  namespace: infra-system
  labels:
    strimzi.io/cluster: main-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "profile-updates"
          patternType: literal
        operations:
          - Read
          - Describe
      - resource:
          type: group
          name: "go-mailer-group"
          patternType: literal
        operations:
          - Read
          - Write
          - Describe
  template:
    secret:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "banking-apps"
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: kafka-keda-user
  namespace: infra-system
  labels:
    strimzi.io/cluster: main-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "profile-updates"
          patternType: literal
        operations:
          - Describe
      - resource:
          type: topic
          name: "balance-requests"
          patternType: literal
        operations:
          - Describe
      - resource:
          type: group
          name: "go-mailer-group"
          patternType: literal
        operations:
          - Describe
      - resource:
          type: group
          name: "cobol-backend-group"
          patternType: literal
        operations:
          - Describe
      # Attention: The KEDA autoscaler only needs Describe permissions to monitor lag, but we can also give it Read permissions for better observability in case we want to check consumer offsets or other details.
      # Write permissions are not strictly necessary for the autoscaler, but they can be useful if we want to allow it to commit offsets or perform other actions in the future.
      - resource:
          type: cluster
        operations:
          - Describe
  template:
    secret:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "banking-apps"
