apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: main-cluster
  namespace: infra-system
  annotations:
    strimzi.io/node-pools: enabled # Enable Connector resources
spec:
  kafka:
    version: 4.2.0
    metadataVersion: "4.2-IV0"
    authorization:
      type: simple
      superUsers:
        - User:ANONYMOUS

    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false # No TLS for this listener, using for development and testing

      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls # mTLS Authentication

      # For COBOL simulation communication
      - name: external
        port: 9094
        type: nodeport
        tls: true
        authentication:
          type: tls # mTLS Authentication
        configuration:
          brokers:
            - broker: 0
              advertisedHost: 192.168.0.103 # IP του talos-68b-si3
            - broker: 1
              advertisedHost: 192.168.0.105 # IP του talos-4zb-66h
            - broker: 2
              advertisedHost: 192.168.0.105 # IP του talos-4zb-66h

    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "4.2.0"

  entityOperator:
    topicOperator: {}
    userOperator: {}
