apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: python-microservice-user
  namespace: infra-system
  labels:
    strimzi.io/cluster: main-cluster
spec:
  authentication:
    type: tls # mTLS Authentication
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operations:
          - Read
          - Describe
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operations:
          - Write
          - Describe
      - resource:
          type: group
          name: "*"
          patternType: literal
        operations:
          - Read
