apiVersion: v1
kind: Service
metadata:
  name: inquiry-backend-service
  namespace: banking-apps
spec:
  selector:
    app: inquiry-backend
  ports:
    - name: java-http-metrics
      protocol: TCP
      port: 80
      nodePort: 31249
      targetPort: 8080
  type: NodePort
