apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mailer-kafka-scaler
  namespace: banking-apps
spec:
  scaleTargetRef:
    name: go-mailer-service
  minReplicaCount: 0
  maxReplicaCount: 20
  cooldownPeriod: 30
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: main-cluster-kafka-bootstrap.infra-system.svc.cluster.local:9093 # Port 9093
        topic: profile-updates
        consumerGroup: go-mailer-group
        lagThreshold: "5"
        authMode: tls
        tls: enable
      authenticationRef:
        name: keda-kafka-auth
